version: "1"
rules:
  - base: master
    upstream: XcodersHub:master    # change `wei` to the owner of upstream repo
    mergeMethod: none
  - base: alpha
    upstream: XcodersHub:alpha
    mergeMethod: none
