version: "1"
rules:
  - base: master
    upstream: KangersHub:master    # change `wei` to the owner of upstream repo
    mergeMethod: none
  - base: alpha
    upstream: KangersHub:alpha
    mergeMethod: none
